### ISSUE TITLE
Trying in Windows 11

### ISSUE THREAD

**Issue by Die2FF** [whoek/scrumdog#3]
Hi,
I try to use scrumdog en Windows 11 to obtain data from Jira OnPremise Server with this error:
Issue accessing 'curl'
Check if you can run 'curl' from command line
Please report an issue to willem@matimba.com
Provide error message below in your email.

Failed: Non 0 exit code Exit code 60
{status=Exit code 60; stderr="";
stdout=""}

***

curl -V
curl 7.88.1 (x86_64-w64-mingw32) libcurl/7.88.1 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.9.0 libgsasl/2.2.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd

Only for your information.
Regards.

**Comment by whoek** [comment]
@Die2FF - `scrumdog` can only download issues from Jira Cloud -- not from OnPremise Server.

If you are using Jira Cloud,  Note that I have made some changes to he code so that it does not rely on `curl` any more. The `curl` dependency did not work for all users.   The latest downloads are available from [here](https://github.com/whoek/scrumdog-binaries).

Thanks
